### ISSUE TITLE
Matomo: add new swedish translations to Matomo

### ISSUE THREAD

**Issue by niklasternstedt** [whitespace-se/matomo-core#6]
# Description
We need to add new translations to Matomo. The translation is quite bad in some cases. For example the invite email is still in english and the settings for darkmode for the theme Modern.

# ToDo – here we can add new todos when we notice translation is missing
- [ ] Invite email
- [ ] Settings for the theme Modern
- [ ] Metrics for custom report

# DoD
- [ ] ToDos checked
- [ ] Translations verified and pushed to core
